### ISSUE TITLE
Emotes in Twitch title messes up the directory 

### ISSUE THREAD

**Issue by MattiSony** [popcorncolonel/Chrome-Extensions#10]
Hey, when someone has a Twitch emote in their title it messes up the directory a bit which is really annoying for me. Here's a picture of how it looks http://i.imgur.com/jxoboy2.jpg and http://i.imgur.com/05hOIKP.jpg

I've even tried to use the blacklist feature but that doesn't seem to work, at least not for Twitch.

**Comment by popcorncolonel** [comment]
I'll look into that, but for now, what are you putting in for the blacklist? Just putting "twitch.tv" for the blacklist works for me.

Thanks for letting me know!

**Comment by MattiSony** [comment]
Just twitch.tv works, thanks. I had twitch.tv/directory/following/live before which didn't work.
