### ISSUE TITLE
Emotes in URL's inside javascript

### ISSUE THREAD

**Issue by dersand** [popcorncolonel/Chrome-Extensions#12]
I'm wondering why a resource of an url wasn't loading, apparently there was an emote in the URL, which messed up when the browser tried to request the resource. 

The case: 
![chrome_2016-03-25_22-02-12](https://cloud.githubusercontent.com/assets/6134511/14053933/4b115382-f2d5-11e5-95ab-6e416c86500e.png)
The line is supposed to be 
`var snd4head =  new Audio(https://pajlada.se/files/clir/.mp3");`

[Here is an URL for debugging](https://paj.pajlada.se/commands/)

**Comment by dersand** [comment]
Maybe something inside do_not_replace?

`if(element.tagName == "SCRIPT"){ return false; }`

**Comment by popcorncolonel** [comment]
Thanks! I'll look into it when I get back from vacation.

**Comment by popcorncolonel** [comment]
Hi,

Is there a site I can test this on? Like a site with a <script> with 4Head
or Kappa in it or something?

Best,
Eric

**Comment by dersand** [comment]
https://paj.pajlada.se/commands/

Click "!#playsound"
Then there's a list if different sounds. The top one has a 4Head un the URL.

**Comment by popcorncolonel** [comment]
Awesome, thanks a bunch! I just fixed it.

The update should be pushed to your device within an hour.
