### ISSUE TITLE
json emote lists get downloaded if a website is blacklisted

### ISSUE THREAD

**Issue by bradzacher** [popcorncolonel/Chrome-Extensions#16]
the downloads shouldn't happen if the website is blacklisted.

especially a problem if the dev tools is open with disable cache ticked, as it will force the extension to download the fresh JSON files (approx 2mb) on each page load.

if I black list a URL, I expect the extension to do nothing on the page.

**Comment by popcorncolonel** [comment]
True that. Tbh, I thought that's how it already worked. But unfortunately, I no longer own the extension -- I sold it to a company. Sorry man.
