### ISSUE TITLE
Img src inherits the protocol prefix from the browser

### ISSUE THREAD

**Issue by quirp** [popcorncolonel/Chrome-Extensions#17]
When I type "Kappa" into google, everything works just fine. But say I have the page as an html file, and load it through the browser as a file on my computer, the img src extensions break because a prefix of "File:" is added. https gives //bbtv..... , while file gives File://bbtv....

Is there an easy fix for this? Any reply would be much appreciated.

**Comment by popcorncolonel** [comment]
Sorry, I no longer own the extension! The solution would be hard coding either "http:" or "https:" in front of the "//"'s, but I can't make this change unfortunately. 

Best,
Eric
