### ISSUE TITLE
Remove console.log from extension

### ISSUE THREAD

**Issue by lefoy** [popcorncolonel/Chrome-Extensions#9]
Please remove all your console.log from the published version of this extension... You should create a develop branch and do your testing there. I had to disable your extension to be able to use my console.
https://gyazo.com/092aacb7ac17393ffc631a29d7adbfdc
Thanks!

**Comment by popcorncolonel** [comment]
Fixed! Thanks for letting me know. I deleted those two lines in my local machine but forgot to hit save on vim.

It should be pushed to all users within 60 minutes.

**Comment by lefoy** [comment]
Thanks for your quick fix! Appreciate it.
